### ISSUE TITLE
Unable to deserialize null to DateTime? using JsonMicrosoftDateTimeConverter

### ISSUE THREAD

**Issue by gavinharriss** [Macross-Software/core#7] opened 2020-05-28 02:01 UTC
When trying to populate a nullable DateTime property from a JSON string with a null value an exception is thrown when employing `JsonMicrosoftDateTimeConverter`.

C#
`[JsonConverter(typeof(JsonMicrosoftDateTimeConverter))]`
`public DateTime? PaymentDueDate { get; set; }`

JSON:
...
`"PaymentDueDate": null,`
...

Exception:
**Message:** 
    System.Text.Json.JsonException : The JSON value could not be converted to System.Nullable 1[System.DateTime]. Path: $.PaymentDueDate | LineNumber: 75 | BytePositionInLine: 28.
**Stack Trace:** 
    JsonDateTimeConverter 1.ReadDateTime(Utf8JsonReader& reader)
    JsonNullableDateTimeConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
    JsonConverter 1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
    JsonPropertyInfo 1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
    ObjectDefaultConverter 1.ReadPropertyValue(Object obj, ReadStack& state, Utf8JsonReader& reader, JsonPropertyInfo jsonPropertyInfo, Boolean useExtensionProperty)
    ObjectDefaultConverter 1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
    JsonConverter 1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
    JsonConverter 1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
    JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
    JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
    JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
    JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
    JsonTests.AdHocDeserialiseTest() line 128
    --- End of stack trace from previous location where exception was thrown ---

**Comment by gavinharriss** [comment] 2020-06-06 05:04
I decided to investigate this further and noticed you had test cases that handle null values. All tests passed when I was experimenting and I wasn't able to fabricate any of my own tests that recreated the issue in a minimal way.

I've come to the conclusion that maybe the underlying JsonConverterFactory might have a bug where it's not serving up the correct converter when different values are mixed together.

After a bit of experimentation I did manage to get deserialization to work in my scenario and am posting the code changes here in case they are useful to anyone else that hits the same issue...

File modified:
https://github.com/Macross-Software/core/blob/develop/ClassLibraries/Macross.Json.Extensions/Code/System.Text.Json.Serialization/JsonMicrosoftDateTimeConverter.cs

```
internal class JsonStandardDateTimeConverter : JsonDateTimeConverter<DateTime>
{
	/// <inheritdoc/>
	public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
		=> ReadDateTime(ref reader) ?? new DateTime();

	...
}
```

```
internal abstract class JsonDateTimeConverter<T> : JsonConverter<T>
{
	...

	public static DateTime? ReadDateTime(ref Utf8JsonReader reader)
	{
		if (reader.TokenType == JsonTokenType.Null)
			return null;

		if (reader.TokenType != JsonTokenType.String)
			throw new JsonException();

		string formatted = reader.GetString();
		Match match = s_Regex.Match(formatted);

		return !match.Success
			|| !long.TryParse(match.Groups[1].Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out long unixTime)
			? throw new JsonException("Unexpected value format, unable to parse DateTime.")
			: s_Epoch.AddMilliseconds(unixTime);
	}
	
	...
}
```

**Comment by CodeBlanch** [comment] 2020-06-13 21:11
@gavinharriss Any way you can give me some code that reproduces the issue? I tried a few things but haven't been successful so far. I would love to debug it and figure out what's going on.

**Comment by CodeBlanch** [comment] 2020-06-13 21:45
Closing the issue but happy to re-open if we get more info.

**Closed** 2020-06-13 21:44 UTC

**Comment by gavinharriss** [comment] 2020-06-14 06:25
@CodeBlanch it's the least I can do to provide some code to reproduce the bug.

It's been an interesting issue trying to provide the code. Originally I was taking a fork of your solution and trying to add the classes I was deserializing to but could not for the life of my reproduce the bug. In the end I've taken my original solution and stripped out everything apart from the bare minimum classes required to reproduce the bug.

I'd be very curious to hear what causes the bug if you can figure it out.

Here's the repo to reproduce the bug - https://github.com/gavinharriss/JsonMicrosoftDateTimeConverterBug

I wonder if somehow the JsonConverterFactory creates the JsonMicrosoftDateTimeConverter for a non-nullable property then decides to re-use it for the nullable property later on, but forgets to apply its null checking logic before attempting to apply it. Might explain why my code tweaks above resolved the issue.

**Comment by CodeBlanch** [comment] 2020-06-15 23:57
Looks like it's a .NET 5 bug. You have this in `Logistics.Services.Unleashed.csproj`:
```xml
<PackageReference Include="System.Net.Http.Json" Version="5.0.0-preview.3.20214.6" />
```
If you take that out, everything works fine. That reference pulls in `System.Text.Json` from preview.3 which seems to have different logic. I tried preview.5, same issue. I'm going to investigate into the System.Text.Json code and probably open an issue with the dotnet/runtime team. I'll link to here when I do that.

**Comment by gavinharriss** [comment] 2020-06-16 00:29
Ah, I'd forgotten I was referencing [HttpClientJsonExtensions](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions?view=net-5.0) to make use of some of the convenience methods. This will have pulled in the System.Net.Http.Json 5.0.0 preview.

Well spotted and thanks for letting me know. Much appreciated.
